# Generated by Django 4.0.2 on 2022-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('volume', models.IntegerField()),
                ('market_code', models.CharField(max_length=100)),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'btc_prices',
            },
        ),
    ]
